### ISSUE TITLE
Using the PCs in differential expression analysis

### ISSUE THREAD

**Issue by evolgen** [heatherjzhou/PCAForQTL#1]
Hi Heather,

Thanks for the wonderful tool. The implementation has been working really well, and its quite straightforward to use since the README is super helpful.

I was wondering if your workflow can be used to explore covariates based on PCAs. The **_filterKnownCovariates_** function outputs the features with less correlation to the PCAs, but is it possible to estimate the correlation of each known covariate with the top PCs.
This is some rough code based on your functions, this was helpful as a sanity check since some of my covariates were uninformative while regressing and I had previously ignored warnings from NA's. But this doesn't inform the PCs to covariates information.

```
require(dplyr)

all_R2values <- groupPredict(dataResponse= knownCovariates, dataPredictors= inferredCovariates, R2Type="unadjusted") 

covariates_R2values <- cbind(colnames(knownCovariates), all_R2values) %>% `colnames<-`(c("knowncovariate", "R2")) %>% as.data.frame() %>% mutate(R2 = as.numeric(R2))

print(covariates_R2values)
```

Would it be a viable application to use the PCs directly for differential expression analysis with interacting terms of the PCs? The use cases are when metadata the design contains the interesting group covariates which shouldn't be added as interaction terms.

Best,
Rohit

**Comment by heatherjzhou** [comment]
Hi Rohit,

Thank you for your kind words! I’m so glad you found our package helpful.

Based on your feedback, I have updated the package so that the `groupPredict()` function is now exported, which means you can now use this function to get R2 values of regressing each known covariate against all the inferred covariates (like you did in your code above). You can find the details by running `?groupPredict`.

From my understanding, SVA is the most popular hidden variable inference method for differential expression analysis. I think that PCs can be used in place of SVs in DE analysis, though I’m not aware of a benchmark study evaluating which method is better for DE. I think that you could have an interaction term between a PC and a known variable if such a choice can be justified, for example, if you have evidence that the PC captures an interesting group covariate.

Best,
Heather

**Comment by evolgen** [comment]
Hi Heather,

Thank you so much for adding it. I tried another variation which provides correlations based on each of the top PC for every covariate, based on your code itself.

```
R2s_all <- NULL
R2s <- rep(NA,ncol(knownCovariates))
for(i in 1:ncol(inferredCovariates)) {
  for(j in 1:ncol(knownCovariates)){
    mod <- lm(knownCovariates[,j] ~ as.matrix(inferredCovariates[,c(1:i)]))
    R2s[j] <- summary(mod)$r.squared
    }
covariates_R2values <- cbind(knownCovariates %>% colnames(), R2s) %>% `colnames<-`(c("knowncovariate", "R2")) %>% as.data.table() %>% mutate(R2 = as.numeric(R2), totPCs = i)
  R2s_all <- rbind(R2s_all, covariates_R2values)
}
print(R2s_all)
```
However, it required knowing where the PCs explain each covariate most, hence something similar to the ElbowDrop function was required. I just used the kneedrop function available in another package ([GNET2](https://www.bioconductor.org/packages/release/bioc/html/GNET2.html)), but I think a modification of ElbowDrop code would be more consistent. Here is my snippet -
```
needed_knowncovariates <- na.omit(R2s_all) %>% dplyr::select(knowncovariate) %>% unname() %>% unlist() %>% unique()
for(colnamecurr in needed_knowncovariates) {
  knee_point_val <- GNET2::kneepointDetection(R2s_all %>% filter(knowncovariate==colnamecurr) %>% dplyr::select(R2) %>% unname() %>% unlist())
  print(paste0(colnamecurr1, " : ", knee_point_val, sep=""))
}
```

The use case is when one of the knowncovariate or a combination of such is to be tested for differential expression. I tried using the topPCs inferred by PCAforQTL, I am naively assuming that extra information about additional PCs needed for a test vs control case represented by a feature/knowncovariate based on adjR2 might help in DEG.
I tested this with Clipper DEGs, and noticed higher overlaps for DEGs using the topPCs inferred from PCAforQTL compared to those without PCs using only known covariates.  I don't have a ground truth dataset or a comparison to DE SVs though :|

Best,
Rohit
